Jahia/jahia-oauth

README.md
pom.xml
src/main/java/org/jahia/modules/jahiaoauth/action/ManageConnectorsSettings.java
src/main/java/org/jahia/modules/jahiaoauth/action/ManageMappers.java
src/main/java/org/jahia/modules/jahiaoauth/decorator/ConnectorNode.java
src/main/java/org/jahia/modules/jahiaoauth/impl/JahiaOAuthServiceImpl.java
src/main/java/org/jahia/modules/jahiaoauth/impl/cache/ClusteredCacheImpl.java
src/main/java/org/jahia/modules/jahiaoauth/impl/cache/EHCacheManagerImpl.java
src/main/java/org/jahia/modules/jahiaoauth/impl/cache/JahiaOAuthCacheServiceImpl.java
src/main/java/org/jahia/modules/jahiaoauth/service/ConnectorService.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthCacheService.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthConstants.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthException.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthService.java
src/main/java/org/jahia/modules/jahiaoauth/service/MapperService.java
src/main/java/org/jahia/modules/jahiaoauth/tag/JahiaOAuthFunctions.java
src/main/java/org/jahia/modules/scribejava/apis/FranceConnectApi.java
src/main/resources/javascript/apps/jahia.json
src/main/resources/javascript/apps/register.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12289
Jahia 8 prep

BACKLOG-12289 Update licence, register with v8, capability

---

pom.xml

- BACKLOG-11947: Use blueprint
- BACKLOG-11947: Use blueprint
- BACKLOG-11947: Use blueprint

BACKLOG 11947

---

pom.xml
src/main/java/org/jahia/modules/jahiaoauth/action/ConnectToOAuthProvider.java
src/main/java/org/jahia/modules/jahiaoauth/action/ManageConnectorsSettings.java
src/main/java/org/jahia/modules/jahiaoauth/action/ManageMappers.java
src/main/java/org/jahia/modules/jahiaoauth/action/OAuthCallback.java
src/main/java/org/jahia/modules/jahiaoauth/impl/JahiaOAuthServiceImpl.java
src/main/java/org/jahia/modules/jahiaoauth/impl/MapperConfig.java
src/main/java/org/jahia/modules/jahiaoauth/impl/Mapping.java
src/main/java/org/jahia/modules/jahiaoauth/impl/OAuthConnectorConfig.java
src/main/java/org/jahia/modules/jahiaoauth/impl/cache/ClusteredCacheImpl.java
src/main/java/org/jahia/modules/jahiaoauth/impl/cache/EHCacheManagerImpl.java
src/main/java/org/jahia/modules/jahiaoauth/impl/cache/JahiaOAuthCacheServiceImpl.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthCacheService.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthConstants.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthService.java
src/main/java/org/jahia/modules/jahiaoauth/tag/JahiaOAuthFunctions.java
src/main/java/org/jahia/modules/jahiaoauth/valves/SSOValve.java
src/main/resources/OSGI-INF/blueprint/blueprint.xml

https://jira.jahia.org/browse/BACKLOG-13899
- Share actions and valve for all connectors, avoid code replication
- Hide configuration implementation details into service, udpate API to use config objects instead of JCR Nodes
- Expose mapper methods for SAML module

BACKLOG-13899

---

src/main/java/org/jahia/modules/jahiaoauth/impl/JahiaOAuthServiceImpl.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthConstants.java

https://jira.jahia.org/browse/BACKLOG-14421

BACKLOG-14421: Allow only one callback URL

---

src/main/resources/OSGI-INF/blueprint/blueprint.xml

https://jira.jahia.org/browse/BACKLOG-14421

BACKLOG-14421: Fixed declaration

---

README.md

https://jira.jahia.org/browse/BACKLOG-14796

[BACKLOG-14796] Add a section about the embedded connectors

---

.circleci/.circleci.settings.xml
.circleci/config.yml
.github/workflows/triggerCircleCIOnPR.yml

https://jira.jahia.org/browse/BACKLOG-14820

BACKLOG-14820: Add CircleCI config

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-14820

BACKLOG-14820: Use released version of dependencies

---

pom.xml

https://jira.jahia.org/browse/DMF-4230

DMF-4230 update module signature

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-15077

BACKLOG-15077 add depends on jahia-authentication

---

README.md
src/main/resources/resources/jahia-oauth_de.properties
src/main/resources/resources/jahia-oauth_en.properties
src/main/resources/resources/jahia-oauth_fr.properties

https://jira.jahia.org/browse/Backlog-15238

Backlog 15238 readme

---

pom.xml
src/main/java/org/jahia/modules/jahiaoauth/impl/JahiaOAuthServiceImpl.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthService.java
src/main/resources/OSGI-INF/blueprint/blueprint.xml

This PR is the signed PR from https://github.com/Jahia/jahia-oauth/pull/27
https://jira.jahia.org/browse/QA-13529

QA-13529: Add or remove Scribe API implementation

---

src/main/resources/joant_facebookButton/html/facebookButton.jsp
src/main/resources/joant_franceConnectButton/html/franceConnectButton.jsp
src/main/resources/joant_githubButton/html/githubButton.jsp
src/main/resources/joant_googleButton/html/googleButton.jsp
src/main/resources/joant_linkedInButton/html/linkedInButton.jsp

https://jira.jahia.org/browse/BACKLOG-15484

Backlog 15484 hide buttons for connected users

---

src/main/java/org/jahia/modules/jahiaoauth/connectors/Connector.java
src/main/java/org/jahia/modules/jahiaoauth/connectors/LinkedInConnectorImpl.java
src/main/java/org/jahia/modules/jahiaoauth/impl/JahiaOAuthServiceImpl.java
src/main/java/org/jahia/modules/jahiaoauth/service/OAuthConnectorService.java
src/main/resources/OSGI-INF/blueprint/blueprint.xml

https://jira.jahia.org/browse/DMF-4327
https://jira.jahia.org/browse/BACKLOG-13972

DMF-4327 - BACKLOG-13972 : fix linkedin connector, make email working

---

src/main/resources/joant_facebookButton/html/facebookButton.jsp
src/main/resources/joant_franceConnectButton/html/franceConnectButton.jsp
src/main/resources/joant_githubButton/html/githubButton.jsp
src/main/resources/joant_googleButton/html/googleButton.jsp
src/main/resources/joant_linkedInButton/html/linkedInButton.jsp

https://jira.jahia.org/browse/BACKLOG-15483

BACKLOG-15483 : displays buttons if ce_preview attribute is present

---

pom.xml
src/main/java/org/jahia/modules/jahiaoauth/action/ConnectToFranceConnect.java
src/main/java/org/jahia/modules/jahiaoauth/action/ConnectToOAuthProvider.java
src/main/java/org/jahia/modules/jahiaoauth/action/FranceConnectFilter.java
src/main/java/org/jahia/modules/jahiaoauth/action/OAuthCallback.java
src/main/java/org/jahia/modules/jahiaoauth/connectors/Connector.java
src/main/java/org/jahia/modules/jahiaoauth/connectors/FacebookConnectorImpl.java
src/main/java/org/jahia/modules/jahiaoauth/connectors/FranceConnectConnectorImpl.java
src/main/java/org/jahia/modules/jahiaoauth/connectors/GithubConnectorImpl.java
src/main/java/org/jahia/modules/jahiaoauth/connectors/GoogleConnectorImpl.java
src/main/java/org/jahia/modules/jahiaoauth/connectors/LinkedInConnectorImpl.java
src/main/java/org/jahia/modules/jahiaoauth/impl/JahiaOAuthServiceImpl.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthConstants.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthException.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthService.java
src/main/java/org/jahia/modules/jahiaoauth/service/OAuthConnectorService.java
src/main/java/org/jahia/modules/scribejava/apis/FranceConnectApi.java
src/main/resources/javascript/facebook-oauth-connector/facebook-controller.js
src/main/resources/javascript/franceconnect-oauth-connector/franceConnect-controller.js
src/main/resources/javascript/github-oauth-connector/github-controller.js
src/main/resources/javascript/google-oauth-connector/google-controller.js
src/main/resources/javascript/linkedin-oauth-connector/linkedIn-controller.js

https://jira.jahia.org/browse/BACKLOG-15482

BACKLOG-15482 : update licence headers

---

pom.xml

https://jira.jahia.org/browse/DMF-3382

DMF-3382 : upgrade scribejava to the latest version

---

.circleci/.circleci.settings.xml

https://jira.jahia.org/browse/BACKLOG-14663

BACKLOG-14663 : fix sonar dependency:check

---

.circleci/config.yml

https://jira.jahia.org/browse/BACKLOG-15472

BACKLOG-15472 : update fingerprint to allow commit on master

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-15600

BACKLOG-15600 : update pom signature

---

.circleci/config.yml

https://jira.jahia.org/browse/PROJECT-XXX
The following are included in this PR
I have considered the following implications of my change:

BACKLOG-15653 Adding changelog and signature to circle ci

---

.circleci/config.yml

This is to align with a change done recently by @bpapez

Updated config to include the latest update to the sonar job in Jahia Orb

---

src/main/java/org/jahia/modules/jahiaoauth/impl/JahiaOAuthServiceImpl.java
src/main/java/org/jahia/modules/jahiaoauth/service/JahiaOAuthConstants.java

https://support.jahia.com/browse/NETSMART-55
https://jira.jahia.org/browse/QA-14016

QA-14016: Expose OpenIdToken for OpenId authentication

---

README.md

QA-14657 - Adding link from readme to academy
